#!/usr/bin/env python3
"""Refresh the portable OMP profile from this machine's live OMP config.

The portable profile is the only channel that carries OMP behavior to another
workstation (`bootstrap-machine.sh` installs it as the new machine's
`config.yml`). Keeping that snapshot by hand is what let it drift: the live
config moved on while the committed snapshot lagged, so a bootstrapped machine
silently received stale routes.

This exporter removes the hand step. It reads the live config, drops the keys
that are machine-local by definition, and refuses to write anything the portable
contract forbids. Every rule about what may travel lives in
`validate_portable_omp_profile.py` and is imported from there: this module owns
extraction, not policy, so the two can never disagree.
"""

from __future__ import annotations

import importlib.util
import os
import sys
from pathlib import Path
from typing import Any, NoReturn

import yaml

SCRIPTS_DIR = Path(__file__).resolve().parent
PROFILE_PATH = SCRIPTS_DIR / "omp-portable-profile.yml"
VALIDATOR_PATH = SCRIPTS_DIR / "validate_portable_omp_profile.py"

HEADER = """# Portable owner-selected OMP profile.
# Authentication, setup completion, consent, sessions, and machine identifiers
# are deliberately absent; bootstrap-machine.sh restores only reusable behavior.
#
# Generated by scripts/export-portable-omp-profile.py from the live OMP config.
# Do not hand-edit: run the exporter on the machine whose behavior should travel,
# then commit the result. A hand edit reintroduces the drift the exporter removes.
"""


def fail(message: str) -> NoReturn:
    raise SystemExit(f"cannot export portable OMP profile: {message}")


def load_validator() -> Any:
    """Import the validator so its rules stay the single source of truth."""
    spec = importlib.util.spec_from_file_location("portable_omp_validator", VALIDATOR_PATH)
    if spec is None or spec.loader is None:
        fail(f"cannot load the portable profile validator at {VALIDATOR_PATH}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def live_config_path(argv: list[str]) -> Path:
    """Resolve the live config exactly as install.sh resolves the OMP base."""
    if len(argv) > 1:
        return Path(argv[1]).expanduser()
    base = os.environ.get("PI_CODING_AGENT_DIR") or str(Path.home() / ".omp" / "agent")
    return Path(base).expanduser() / "config.yml"


def portable_snapshot(live: dict[str, Any], machine_only: frozenset[str]) -> dict[str, Any]:
    """Drop machine-local roots and keep the owner-selected behavior in order."""
    return {key: value for key, value in live.items() if key not in machine_only}


def main(argv: list[str]) -> int:
    validator = load_validator()
    source = live_config_path(argv)
    try:
        live = yaml.safe_load(source.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, yaml.YAMLError) as error:
        fail(f"cannot read the live OMP config {source}: {error}")
    if not isinstance(live, dict) or not live:
        fail(f"the live OMP config {source} is not a non-empty mapping")

    snapshot = portable_snapshot(live, validator.MACHINE_ONLY_ROOT_KEYS)
    # Fail closed before writing: a rejected snapshot must never replace the
    # committed one, or a secret-bearing profile could reach the repository.
    validator.validate_profile(snapshot)

    body = yaml.safe_dump(snapshot, allow_unicode=True, sort_keys=False, default_flow_style=False)
    PROFILE_PATH.write_text(HEADER + body, encoding="utf-8")
    dropped = sorted(set(live) - set(snapshot))
    print(f"portable OMP profile exported from {source} to {PROFILE_PATH}")
    print(f"machine-local roots dropped: {', '.join(dropped) if dropped else '<none>'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
